exclude: '.pytest_cache|.git'
default_stages: [commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ['--config=.flake8']
        additional_dependencies: [flake8-isort, flake8-tidy-imports, flake8-coding, flake8-broken-line, flake8-bugbear]

#  - repo: https://github.com/PyCQA/bandit
#    rev: 1.7.0
#    hooks:
#      - id: bandit
#        name: bandit
#        description: 'Bandit is a tool for finding common security issues in Python code'

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        additional_dependencies: [pydantic==1.8.2, mypy-extensions==0.4.3, typed-ast==1.4.3, typing-extensions==3.10.0.0]
